// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Paschoalotto.People.Infrastructure.Persistence;

#nullable disable

namespace Paschoalotto.People.Infrastructure.Migrations
{
    [DbContext(typeof(PeopleDbContext))]
    partial class PeopleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("Paschoalotto.People.Domain.People.Individual", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhotoPath")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FullName");

                    b.ToTable("Individuals", (string)null);
                });

            modelBuilder.Entity("Paschoalotto.People.Domain.People.LegalEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorporateName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LegalRepresentativeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoPath")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("MunicipalRegistration")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("StateRegistration")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("TradeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CorporateName");

                    b.HasIndex("TradeName");

                    b.ToTable("LegalEntities", (string)null);
                });

            modelBuilder.Entity("Paschoalotto.People.Domain.People.Individual", b =>
                {
                    b.OwnsOne("Paschoalotto.People.Domain.People.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("IndividualId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("TEXT")
                                .HasColumnName("City");

                            b1.Property<string>("Complement")
                                .HasMaxLength(60)
                                .HasColumnType("TEXT")
                                .HasColumnName("Complement");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("TEXT")
                                .HasColumnName("Country");

                            b1.Property<string>("District")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("TEXT")
                                .HasColumnName("District");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(15)
                                .HasColumnType("TEXT")
                                .HasColumnName("Number");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("TEXT")
                                .HasColumnName("State");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("TEXT")
                                .HasColumnName("Street");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT")
                                .HasColumnName("ZipCode");

                            b1.HasKey("IndividualId");

                            b1.ToTable("Individuals");

                            b1.WithOwner()
                                .HasForeignKey("IndividualId");
                        });

                    b.OwnsOne("Paschoalotto.People.Domain.People.ValueObjects.Cpf", "Cpf", b1 =>
                        {
                            b1.Property<Guid>("IndividualId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("TEXT")
                                .HasColumnName("Cpf");

                            b1.HasKey("IndividualId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("Individuals");

                            b1.WithOwner()
                                .HasForeignKey("IndividualId");
                        });

                    b.OwnsOne("Paschoalotto.People.Domain.People.ValueObjects.EmailAddress", "Email", b1 =>
                        {
                            b1.Property<Guid>("IndividualId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("TEXT")
                                .HasColumnName("Email");

                            b1.HasKey("IndividualId");

                            b1.HasIndex("Value");

                            b1.ToTable("Individuals");

                            b1.WithOwner()
                                .HasForeignKey("IndividualId");
                        });

                    b.OwnsOne("Paschoalotto.People.Domain.People.ValueObjects.PhoneNumber", "Phone", b1 =>
                        {
                            b1.Property<Guid>("IndividualId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("TEXT")
                                .HasColumnName("Phone");

                            b1.HasKey("IndividualId");

                            b1.ToTable("Individuals");

                            b1.WithOwner()
                                .HasForeignKey("IndividualId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Cpf")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Phone")
                        .IsRequired();
                });

            modelBuilder.Entity("Paschoalotto.People.Domain.People.LegalEntity", b =>
                {
                    b.OwnsOne("Paschoalotto.People.Domain.People.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("LegalEntityId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("TEXT")
                                .HasColumnName("City");

                            b1.Property<string>("Complement")
                                .HasMaxLength(60)
                                .HasColumnType("TEXT")
                                .HasColumnName("Complement");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("TEXT")
                                .HasColumnName("Country");

                            b1.Property<string>("District")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("TEXT")
                                .HasColumnName("District");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(15)
                                .HasColumnType("TEXT")
                                .HasColumnName("Number");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(40)
                                .HasColumnType("TEXT")
                                .HasColumnName("State");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("TEXT")
                                .HasColumnName("Street");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT")
                                .HasColumnName("ZipCode");

                            b1.HasKey("LegalEntityId");

                            b1.ToTable("LegalEntities");

                            b1.WithOwner()
                                .HasForeignKey("LegalEntityId");
                        });

                    b.OwnsOne("Paschoalotto.People.Domain.People.ValueObjects.EmailAddress", "Email", b1 =>
                        {
                            b1.Property<Guid>("LegalEntityId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("TEXT")
                                .HasColumnName("Email");

                            b1.HasKey("LegalEntityId");

                            b1.HasIndex("Value");

                            b1.ToTable("LegalEntities");

                            b1.WithOwner()
                                .HasForeignKey("LegalEntityId");
                        });

                    b.OwnsOne("Paschoalotto.People.Domain.People.ValueObjects.Cpf", "LegalRepresentativeCpf", b1 =>
                        {
                            b1.Property<Guid>("LegalEntityId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("TEXT")
                                .HasColumnName("LegalRepCpf");

                            b1.HasKey("LegalEntityId");

                            b1.HasIndex("Value");

                            b1.ToTable("LegalEntities");

                            b1.WithOwner()
                                .HasForeignKey("LegalEntityId");
                        });

                    b.OwnsOne("Paschoalotto.People.Domain.People.ValueObjects.PhoneNumber", "Phone", b1 =>
                        {
                            b1.Property<Guid>("LegalEntityId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("TEXT")
                                .HasColumnName("Phone");

                            b1.HasKey("LegalEntityId");

                            b1.ToTable("LegalEntities");

                            b1.WithOwner()
                                .HasForeignKey("LegalEntityId");
                        });

                    b.OwnsOne("Paschoalotto.People.Domain.People.ValueObjects.Cnpj", "Cnpj", b1 =>
                        {
                            b1.Property<Guid>("LegalEntityId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(14)
                                .HasColumnType("TEXT")
                                .HasColumnName("Cnpj");

                            b1.HasKey("LegalEntityId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("LegalEntities");

                            b1.WithOwner()
                                .HasForeignKey("LegalEntityId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Cnpj")
                        .IsRequired();

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("LegalRepresentativeCpf")
                        .IsRequired();

                    b.Navigation("Phone")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
